askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect,render
from django.views.generic import RedirectView

# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$', root, name='root'),
    # url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^$', lambda request: render(request, 'root.html'), name='root'),
    # url(r'^$', RedirectView.as_view(pattern_name='blog:post_list')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    # auth앱과 연동할건데, django.contrib.auth urls에는 namespace가 적용이 되어 있지 않기 때문에 accounts 앱에서도 namespace를 쓰지 않는다.
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
# blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'), # 포스팅 목록
    # url(r'^$', views_cbv.post_list, name='post_list'), # 포스팅 목록(CBV)
    
    url(r'^new/$', views.post_new, name='post_new'), # 새 포스팅
    # url(r'^cbv/new/$', views_cbv.post_new, name='post_new'), # 새 포스팅 (CBV)
    
    # url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'), # 포스팅 보기(post_detail일 함수는 id라는 이름의 필드를 받을수 있어야한다)
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'), # 포스팅 보기(CBV)

    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'), # 포스팅 수정
    # url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit, name='post_edit'), # 포스팅 수정(CBV)
    
    # url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='post_delete'), # 포스팅 삭제(구현안함)
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name='post_delete'), # 포스팅 삭제(CBV)
    
    url(r'^comments/$', views.comment_list, name='comment_list'), #

    url(r'^(?P<post_id>\d+)/comments/new$', views.comment_new, name='comment_new'), # 댓글 생성
    url(r'^(?P<post_id>\d+)/comments/(?P<id>\d+)/edit/$', views.comment_edit, name='comment_edit'),# 댓글 수정
    url(r'^(?P<post_id>\d+)/comments/(?P<id>\d+)/delete/$', views.comment_delete, name='comment_delete'),# 댓글 삭제
]

#정규표현식: ^: 문자열의 시작, $: 문자열의 끝, 따라서 아무런 문자열이 없다, 즉, 최상위 주소 패턴을 의미한다.
#views에 post_list 함수 자체를 넘겨준다. 파이썬은 1급함수를 지원하는 언어이기때문에, 함수를 인자로써 넘겨 줄 수 있다.
#List 는 순서가 있는 자료구조
#요청이 들어오면 순서대로 url맵핑한다. 맵핑되면 return으로 url을 줌.

# (?P ) : 이 영역의 문자열에 정규표현식을 적용해서
# \d+ : \d+ 패턴에 부합된다면
# <x> : x 라는 변수명으로 인자를 넘기겠다.

# 뷰의 인자로 넘겨받은 값들은 모두 문자열 타입입니다.

blog/models.py
#blog/models.py
import re
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.forms import ValidationError
from imagekit.models import ImageSpecField,ProcessedImageField
from imagekit.processors import Thumbnail

def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value): # [+-]? : +,- 가 없거나 한개있으면
        raise ValidationError('Invalid LngLat Type')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # author = models.CharField(max_length=20)
    title = models.CharField(max_length=100, verbose_name='제목',
        help_text='포스팅 제목을 입력해주세요. 최대 100자 내외. ') #길이 제한있는 문자열
    content = models.TextField(verbose_name='내용')            #길이 제한이 없는 문자열(쿼리성능이 안좋아져서 타이트하게 지정)
    
    # 1) 원본이미지 저장, 썸네일 처리
    # photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d') #pillow 설치필요, upload_to상대경로
    # photo_thumbnail = ImageSpecField(source='photo',
    #         processors=[Thumbnail(300,300)],
    #         format = 'JPEG',
    #         options={'quality':60},
    #         )
    
    # 2) 원본 이미지 저장 없이, 썸네일 처리
    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
            processors=[Thumbnail(300,300)],
            format = 'JPEG',
            options={'quality':60},
            )

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=100, blank=True, 
        validators=[lnglat_validator], #함수자체를 넘김
        help_text='경도/위도 포맷으로 입력')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True) #같은 앱에 있는 Tag라는 모델과 relation을 건다. 다른앱: 'auth.Tag'
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])
    # 해당 post=Post.object.first() 
    # resolve_url(post) 이함수는 인자에 get_absolute_url 어트리뷰트가 있는지 확인해서 있으면 그 함수를 호출,리턴해줌
    

class Comment(models.Model):
    post = models.ForeignKey(Post) #post_id
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']
    
    def get_edit_url(self):
        return reverse('blog:comment_edit', args=[self.post.id, self.id])
    def get_delete_url(self):
        return reverse('blog:comment_delete', args=[self.post.id, self.id])

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from askdjango.widgets.naver_map_point_widget import NaverMapPointWidget
from .models import Post,Comment

class PostForm(forms.ModelForm):
    # dummy = forms.CharField(widget=NaverMapPointWidget(attrs={'width': "100%",'height': 200}))

    class Meta:
        model = Post
        fields='__all__'
        widgets={
            'lnglat': NaverMapPointWidget(attrs={'width': 600,'height': 300}),
        }
        #위젯을 클래스로 지정해도되고 인스턴스로 지정해도됨.


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

blog/views.py
# blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.views.generic import ListView

def post_list(request): #(Post->Comment 접근)
    # print(request.user.is_authenticated)
    qs = Post.objects.all().prefetch_related('tag_set')
    #MtoM or FK의 reverse relation
    #각 관계 별로 DB쿼리를 수행하고, 파이썬 단에서 조인을 수행
    q = request.GET.get('q','') #request get 쿼리셋어 q가있으면 가져오고, 없으면 빈문자열
    if q:
        qs = qs.filter(title__icontains=q)

    ctx={
        'post_list': qs,
        'q' : q,
    }
    return render(request, 'blog/post_list.html',ctx)

# post_list = ListView.as_view(model=Post, paginate_by=10)
    
    # HttpResponse 인스턴스인데, render를 통해서, 좀 더 쉽게 템플릿을 통한 렌더링
    # response=render(request, 'blog/post_list.html',ctx)
    # return response

'''
파이썬 dict타입에서도 지원하는 인터페이스입니다. request.GET은 QuerySet타입으로서, dict과 유사한 인터페이스를 제공해주고 있습니다.
QuerySet의 get함수는 인자를 1개 받기도 하고, 2개 받을 수도 있습니다.

>>> queryset[접근Key] # 지정 Key의 값 반환을 시도. 지정 Key가 없을 때 KeyError 예외가 발생합니다.

>>> queryset.get(접근Key) # 지정 Key의 값 반환을 시도. 지정 Key가 없을 때 KeyError 예외가 발생합니다.

>>> queryset.get(접근Key, 디폴트값) # queryset에 지정Key가 없을 때, KeyError 예외가 발생하지 않고, 2번째 인자로 지정한 디폴트값이 리턴됩니다.
'''

def post_detail(request, id):
    #url창에 localhost:8000/blog/10 을 적어주면, id=10을 받는다
    #Post 게시물 하나를 지우고 다시 접근하면 서버에러 500을 발생시킴
    #서버에러가 아니기때문에 Http404에러를 발생시켜줘야한다.
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404
    post = get_object_or_404(Post, id=id)

    ctx={
        'post':post,
    }
    return render(request, 'blog/post_detail.html', ctx)

# Post.objects.all() 은 QuerySet 이며,

# QuerySet 의 filter 와 exclude, order_by 리턴값은 QuerySet 입니다.
# QuerySet 의 get 리턴값은 해당 모델의 인스턴스이구요.
# 잘 안 넘어간다고 하신. 아래 코드에서도 QuerySet 인스턴스가 post 변수에 담겨집니다.

# post = Post.objects.all().filter(id=pk)

def post_new(request):
    if request.method=='POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post) #post.get_absolute_url() => post detail
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form':form,
    })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method=='POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request,'포스팅을 수정했습니다.')
            return redirect(post) #post.get_absolute_url() => post detail
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form':form,
    })

def comment_list(request): #테스트를 위해 함수구현(Comment->Post 접근)
    comment_list = Comment.objects.all().select_related('post') 
    #Comment에 대한 sql을 요청할때 한번에 같이 Post sql을 요청한다.
    #외래키 or 원투원 필드를 쓸 때 활용. 생성되는 sql수를 현저하게 줄일 수 있다. 
    # SELECT ••• FROM "blog_comment" INNER JOIN "blog_post" ON ("blog_comment"."post_id" = "blog_post"."id")
    return render(request, 'blog/comment_list.html',{
        'comment_list' : comment_list,    
    })

@login_required
def comment_new(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {
        'form' : form,
    })

@login_required
def comment_edit(request, post_id, id):
    comment = get_object_or_404(Comment, pk=id)
    if comment.author != request.user:
        return redirect(comment.post)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save()

            
             
            return redirect(comment.post)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment_form.html', {
        'form' : form,
    })


@login_required
def comment_delete(request, post_id, id):
    comment = get_object_or_404(Comment, pk=id)
    if comment.author != request.user:
        return redirect(comment.post)

    if request.method == 'POST':
        comment.delete()
        return redirect(comment.post)
    
    return render(request, 'blog/comment_confirm_delete.html', {
        'comment' : comment,
    })

blog/templates/blog/comment_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    
    정말 삭제하시겠습니까?
    
    <input type="submit" value="삭제하겠습니다." />
</form>

blog/templates/blog/comment_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

blog/templates/blog/comment_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <ul>
        {% for comment in comment_list %}
        <li>
            {{ comment }}
            {{ comment.post }}
        </li>
        {% endfor %}    
    </ul>
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html"%}

{% block title %}AskDjango's Blog{% endblock%}

blog/templates/blog/post_confirm_delete.html
<h1>{{ post }} 삭제 확인</h1>

정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}">아니요. 취소하겠습니다.</a>
    <input type="submit" value="예, 삭제하겠습니다." />
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>
                
                {% if post.photo %}
                {% comment %} <img src="/media/{{ post.photo }}" style="max_width: 100%;" /> {% endcomment %}
                {% comment %} 방법1 원본저장)<img src="{{ post.photo_thumbnail.url }}" style="max_width: 100%;" /> {% endcomment %}
                {% comment %} 방법2 원본미저장)<img src="{{ post.photo.url }}" style="max_width: 100%;" /> {% endcomment %}
                {% comment %} 방법3-1 템플릿){% thumbnail "100x100" post.photo as thumb %}     {% endcomment %}
                {% comment %} 방법3-2 템플릿){% thumbnail "100x100" post.photo as thumb %}
                    <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" /> {% endcomment %}
                    {% comment %} 방법3-3 템플릿){% endcomment %}
                    {% thumbnail "100x100" post.photo -- style="" onclick="" class="" %} 
                {% endif %}

                {{ post.content | linebreaks }}
                {% comment %} {{ post.content | linebreaksbr }} {% endcomment %}
            
                <hr/>
            
                <h3>Comments</h3>
            
                <ul>
                    {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.updated_at }}</small>
                        {% if comment.author == request.user %}
                            <small><a href="{{ comment.get_edit_url }}">수정</a></small>
                            <small><a href="{{ comment.get_delete_url }}">삭제</a></small>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            
                <hr/>
                <a href="{% url "blog:post_list" %}" class="btn btn-primary">글목록</a> 
                <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">글수정</a>
                <a href="{% url "blog:comment_new" post.id %}" class="btn btn-success">댓글쓰기</a> 
                {% comment %} {% url "namespace: URL reversename " 인자 %} {% endcomment %}
                {% comment %} 인자가 없으니 안넘겨도됨 {% endcomment %}
                {% comment %} {{ post.get_absolute_url }} 도 가능{% endcomment %}
            </div>
        </div>
    </div>
    
{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
{% comment %}
 post 방식일때, enctype 웹브라우저가 서버로 파일 전송함! 
 파일이업로드 안된다? 두가지 확인.
 1.enctype여부
 2.views.py에 request.POST, request.FILES 지정
{% endcomment %}
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h1>Django Template <sup>by AskDjango</sup></h1>
            <p>여러분의 파이썬/장고 페이스메이커가 되겠습니다.</p>
            <p>
                <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                    AskDjango 페이스북 그룹 &raquo;
                </a>
            </p>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-info">
                    <ul>
                        <li> 
                            <a href="https://youtu.be/SMMaUgGeupQ">착한애견 Tv 클릭해보세요.</a>
                        </li>
                    </ul>
                </div>
                
                <a href="{% url "blog:post_new" %}" class='btn btn-primary pull-right'>New Post</a>

                <p>
                    <form action="" method="get">
                        <input type="text" name='q' value="{{ q }}">
                        <input type="submit" value='검색' class="btn btn-primary">
                    </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>author</th>
                            <th>updated_at</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post_list %}
                        <tr>
                            <td>{{ post.id }}</td>
                            <td><a href="{% url "blog:post_detail" post.id %}">{{ post.title }}</a>
                                {% for tag in post.tag_set.all %}
                                    <span class="label label-info">{{ tag.name }}</span>
                                {% endfor %}
                            </td>
                             {% comment %} <a href="/blog/{{ post.id }}/">
                                    {{ post.title }}
                            </a> {% endcomment %}
                            <td><small>by {{ post.author}}</small></td>
                            <td><small>at {{ post.updated_at}}</small></td>
                            {% comment %} <td>{{ post.comment_set.all }}</td> {% endcomment %}
                        </tr>
                        {% endfor %}    
                    </tbody>
                </table>
            </div>
        </div>
    
    </div>

    
{% endblock %}


{% comment %} {% load bootstrap3 staticfiles %}
{% bootstrap_css %}
{% bootstrap_javascript %} 

<table class="table table-bordered table-hover">
    <caption>Post List</caption>
    <thead>
        <tr>
            <th>title</th>
            <th>created at</th>
        </tr>
    </thead>
    <tbody>
        {% for post in post_list %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.updated_at }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="text-center">
 {% bootstrap_pagination page_obj %}
</div> {% endcomment %}